### PR TITLE
Update brave logos to the latest and greatest

### PR DESCRIPTION
**Pull request by Jacalz**
Updates the logos of the Brave browser to the latest logo from Brave

### CODE REVIEW

**Comment by kspearrin** [comment]
Your updated logo is very pixelated. All of these logos come from https://github.com/alrra/browser-logos . Perhaps you should issue a PR there and then we go pull from that as the upstream?

**Comment by Jacalz** [comment]
Ah I see 😅 I used a downscale to scale the icons down, are you getting these icons in those sizes directly from upstream?

**Comment by Jacalz** [comment]
I did open an issue upstream, where I asked them to update the logo 😉

**Comment by Jacalz** [comment]
Let’s close this for now and I can open a new or when they update upstream 🙂

**Comment by Jacalz** [comment]
I just want to update you on this Kyle. The logos have been updated upstream but they are only updated to the ones that are currently the ones in 0.19.x! There will be new logos coming in 0.20.x and that realease will be fairly soon with only 20 open issues left on the milestone for it. I am going to wait for 0.20x to release and then update logos upstream and make a pr here when that is done 🙂

**Pull request closed without merging**
